# Generated by Django 4.1.5 on 2023-01-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('type_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_from', to='cash.currency')),
                ('type_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_to', to='cash.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('conversation_rate', models.FloatField(max_length=10)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.currency')),
            ],
        ),
    ]
