# Generated by Django 4.1.5 on 2023-01-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_query_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='type_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_from', to='cash.currency'),
        ),
        migrations.AlterField(
            model_name='query',
            name='type_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_to', to='cash.currency'),
        ),
    ]
