# Generated by Django 4.1.5 on 2023-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_remove_query_type_from_remove_query_type_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
